version: 2.1

orbs:
  python: circleci/python@0.2.1
  gh-pages: sugarshin/gh-pages@1.0.0

branches:
  only:
    - master

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          command: git pull
      - run:
          command: pip install flask Frozen-Flask pyyaml gitpython
      - run: 
          command: python cookbook/freeze.py
      - gh-pages/deploy:
          setup-git: true
          ssh-fingerprints: d9:9f:13:4a:ee:7f:18:a9:da:bd:29:21:bd:17:af:4f
 
workflows:
  main:
    jobs:
      - build